branches:
  only:
    - master

matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "6"
      script:
        - npm i
        - npm run tslint
    - stage: "WebPack"
      os: osx
      env:
        - WebpackiOS="11"
      osx_image: xcode9.1
      language: node_js
      node_js: "6"
      jdk: oraclejdk8
      script:
        - npm i
        - npm run compile
        - cd demo
        - npm i
        - npm run ns-bundle --ios --build-app --uglify
        - cd ../demo-angular
        - npm i
        - npm run ns-bundle --ios --build-app --uglify
    - language: android
      os: linux
      env:
        - WebpackAndroid="26"
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script:
        - npm i
        - npm run compile
        - cd demo
        - npm i
        - npm run ns-bundle --android --build-app --uglify --snapshot
        - cd ../demo-angular
        - npm i
        - npm run ns-bundle --android --build-app --uglify --snapshot
    - stage: "Build"
      language: android
      env:
        - BuildAndroid="26"
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script:
        - npm i
        - npm run compile
        - cd demo
        - npm i
        - tns build android
        - cd ../demo-angular
        - npm i
        - tns build android
    - os: osx
      env:
        - BuildiOS="11"
        - Xcode="9.1"
      osx_image: xcode9.1
      language: node_js
      node_js: "6"
      jdk: oraclejdk8
      script:
        - npm i
        - npm run compile
        - cd demo
        - npm i
        - tns build ios
        - cd ../demo-angular
        - npm i
        - tns build ios

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - android-23
    - extra-android-m2repository

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
